export const countries = [
  { longName: "United States", shortName: "US" },
  { longName: "Afghanistan", shortName: "AF" },
  { longName: "Albania", shortName: "AL" },
  { longName: "Algeria", shortName: "DZ" },
  { longName: "American Samoa", shortName: "AS" },
  { longName: "Andorra", shortName: "AD" },
  { longName: "Angola", shortName: "AO" },
  { longName: "Anguilla", shortName: "AI" },
  { longName: "Antarctica", shortName: "AQ" },
  { longName: "Antigua and Barbuda", shortName: "AG" },
  { longName: "Argentina", shortName: "AR" },
  { longName: "Armenia", shortName: "AM" },
  { longName: "Aruba", shortName: "AW" },
  { longName: "Australia", shortName: "AU" },
  { longName: "Austria", shortName: "AT" },
  { longName: "Azerbaijan", shortName: "AZ" },
  { longName: "Bahamas", shortName: "BS" },
  { longName: "Bahrain", shortName: "BH" },
  { longName: "Bangladesh", shortName: "BD" },
  { longName: "Barbados", shortName: "BB" },
  { longName: "Belarus", shortName: "BY" },
  { longName: "Belgium", shortName: "BE" },
  { longName: "Belize", shortName: "BZ" },
  { longName: "Benin", shortName: "BJ" },
  { longName: "Bermuda", shortName: "BM" },
  { longName: "Bhutan", shortName: "BT" },
  { longName: "Bolivia", shortName: "BO" },
  { longName: "Bonaire", shortName: "BQ" },
  { longName: "Bosnia and Herzegovina", shortName: "BA" },
  { longName: "Botswana", shortName: "BW" },
  { longName: "Bouvet Island", shortName: "BV" },
  { longName: "Brazil", shortName: "BR" },
  { longName: "British Indian Ocean Territory", shortName: "IO" },
  { longName: "Brunei Darussalam", shortName: "BN" },
  { longName: "Bulgaria", shortName: "BG" },
  { longName: "Burkina Faso", shortName: "BF" },
  { longName: "Burundi", shortName: "BI" },
  { longName: "Cambodia", shortName: "KH" },
  { longName: "Cameroon", shortName: "CM" },
  { longName: "Canada", shortName: "CA" },
  { longName: "Cape Verde", shortName: "CV" },
  { longName: "Cayman Islands", shortName: "KY" },
  { longName: "Central African Republic", shortName: "CF" },
  { longName: "Chad", shortName: "TD" },
  { longName: "Chile", shortName: "CL" },
  { longName: "China", shortName: "CN" },
  { longName: "Christmas Island", shortName: "CX" },
  { longName: "Cocos (Keeling) Islands", shortName: "CC" },
  { longName: "Colombia", shortName: "CO" },
  { longName: "Comoros", shortName: "KM" },
  { longName: "Congo", shortName: "CG" },
  { longName: "Congo, The Democratic Republic of the", shortName: "CD" },
  { longName: "Cook Islands", shortName: "CK" },
  { longName: "Costa Rica", shortName: "CR" },
  { longName: 'Cote D"Ivoire', shortName: "CI" },
  { longName: "Croatia", shortName: "HR" },
  { longName: "Cuba", shortName: "CU" },
  { longName: "Curacao", shortName: "CW" },
  { longName: "Cyprus", shortName: "CY" },
  { longName: "Czech Republic", shortName: "CZ" },
  { longName: "Denmark", shortName: "DK" },
  { longName: "Djibouti", shortName: "DJ" },
  { longName: "Dominica", shortName: "DM" },
  { longName: "Dominican Republic", shortName: "DO" },
  { longName: "Ecuador", shortName: "EC" },
  { longName: "Egypt", shortName: "EG" },
  { longName: "El Salvador", shortName: "SV" },
  { longName: "Equatorial Guinea", shortName: "GQ" },
  { longName: "Eritrea", shortName: "ER" },
  { longName: "Estonia", shortName: "EE" },
  { longName: "Eswatini", shortName: "SZ" },
  { longName: "Ethiopia", shortName: "ET" },
  { longName: "Falkland Islands (Malvinas)", shortName: "FK" },
  { longName: "Faroe Islands", shortName: "FO" },
  { longName: "Fiji", shortName: "FJ" },
  { longName: "Finland", shortName: "FI" },
  { longName: "France", shortName: "FR" },
  { longName: "French Guiana", shortName: "GF" },
  { longName: "French Polynesia", shortName: "PF" },
  { longName: "French Southern Territories", shortName: "TF" },
  { longName: "Gabon", shortName: "GA" },
  { longName: "Gambia", shortName: "GM" },
  { longName: "Georgia", shortName: "GE" },
  { longName: "Germany", shortName: "DE" },
  { longName: "Ghana", shortName: "GH" },
  { longName: "Gibraltar", shortName: "GI" },
  { longName: "Greece", shortName: "GR" },
  { longName: "Greenland", shortName: "GL" },
  { longName: "Grenada", shortName: "GD" },
  { longName: "Guadeloupe", shortName: "GP" },
  { longName: "Guam", shortName: "GU" },
  { longName: "Guatemala", shortName: "GT" },
  { longName: "Guernsey", shortName: "GG" },
  { longName: "Guinea", shortName: "GN" },
  { longName: "Guinea-Bissau", shortName: "GW" },
  { longName: "Guyana", shortName: "GY" },
  { longName: "Haiti", shortName: "HT" },
  { longName: "Heard Island and Mcdonald Islands", shortName: "HM" },
  { longName: "Holy See (Vatican City State)", shortName: "VA" },
  { longName: "Honduras", shortName: "HN" },
  { longName: "Hong Kong", shortName: "HK" },
  { longName: "Hungary", shortName: "HU" },
  { longName: "Iceland", shortName: "IS" },
  { longName: "India", shortName: "IN" },
  { longName: "Indonesia", shortName: "ID" },
  { longName: "Iran, Islamic Republic Of", shortName: "IR" },
  { longName: "Iraq", shortName: "IQ" },
  { longName: "Ireland", shortName: "IE" },
  { longName: "Isle of Man", shortName: "IM" },
  { longName: "Israel", shortName: "IL" },
  { longName: "Italy", shortName: "IT" },
  { longName: "Ivory Coast", shortName: "CI" },
  { longName: "Jamaica", shortName: "JM" },
  { longName: "Japan", shortName: "JP" },
  { longName: "Jersey", shortName: "JE" },
  { longName: "Jordan", shortName: "JO" },
  { longName: "Kazakhstan", shortName: "KZ" },
  { longName: "Kenya", shortName: "KE" },
  { longName: "Kiribati", shortName: "KI" },
  { longName: 'Korea, Democratic People"S Republic of', shortName: "KP" },
  { longName: "Korea, Republic of", shortName: "KR" },
  { longName: "Kuwait", shortName: "KW" },
  { longName: "Kyrgyzstan", shortName: "KG" },
  { longName: 'Lao People"S Democratic Republic', shortName: "LA" },
  { longName: "Laos", shortName: "LA" },
  { longName: "Latvia", shortName: "LV" },
  { longName: "Lebanon", shortName: "LB" },
  { longName: "Lesotho", shortName: "LS" },
  { longName: "Liberia", shortName: "LR" },
  { longName: "Libyan Arab Jamahiriya", shortName: "LY" },
  { longName: "Liechtenstein", shortName: "LI" },
  { longName: "Lithuania", shortName: "LT" },
  { longName: "Luxembourg", shortName: "LU" },
  { longName: "Macao", shortName: "MO" },
  { longName: "Macedonia, The Former Yugoslav Republic of", shortName: "MK" },
  { longName: "Madagascar", shortName: "MG" },
  { longName: "Malawi", shortName: "MW" },
  { longName: "Malaysia", shortName: "MY" },
  { longName: "Maldives", shortName: "MV" },
  { longName: "Mali", shortName: "ML" },
  { longName: "Malta", shortName: "MT" },
  { longName: "Marshall Islands", shortName: "MH" },
  { longName: "Martinique", shortName: "MQ" },
  { longName: "Mauritania", shortName: "MR" },
  { longName: "Mauritius", shortName: "MU" },
  { longName: "Mayotte", shortName: "YT" },
  { longName: "Mexico", shortName: "MX" },
  { longName: "Micronesia, Federated States of", shortName: "FM" },
  { longName: "Moldova, Republic of", shortName: "MD" },
  { longName: "Monaco", shortName: "MC" },
  { longName: "Mongolia", shortName: "MN" },
  { longName: "Montenegro", shortName: "ME" },
  { longName: "Montserrat", shortName: "MS" },
  { longName: "Morocco", shortName: "MA" },
  { longName: "Mozambique", shortName: "MZ" },
  { longName: "Myanmar", shortName: "MM" },
  { longName: "Namibia", shortName: "NA" },
  { longName: "Nauru", shortName: "NR" },
  { longName: "Nepal", shortName: "NP" },
  { longName: "Netherlands", shortName: "NL" },
  { longName: "Netherlands Antilles", shortName: "AN" },
  { longName: "New Caledonia", shortName: "NC" },
  { longName: "New Zealand", shortName: "NZ" },
  { longName: "Nicaragua", shortName: "NI" },
  { longName: "Niger", shortName: "NE" },
  { longName: "Nigeria", shortName: "NG" },
  { longName: "Niue", shortName: "NU" },
  { longName: "Norfolk Island", shortName: "NF" },
  { longName: "Northern Mariana Islands", shortName: "MP" },
  { longName: "Norway", shortName: "NO" },
  { longName: "Oman", shortName: "OM" },
  { longName: "Pakistan", shortName: "PK" },
  { longName: "Palau", shortName: "PW" },
  { longName: "Palestinian Territory, Occupied", shortName: "PS" },
  { longName: "Panama", shortName: "PA" },
  { longName: "Papua New Guinea", shortName: "PG" },
  { longName: "Paraguay", shortName: "PY" },
  { longName: "Peru", shortName: "PE" },
  { longName: "Philippines", shortName: "PH" },
  { longName: "Pitcairn", shortName: "PN" },
  { longName: "Poland", shortName: "PL" },
  { longName: "Portugal", shortName: "PT" },
  { longName: "Puerto Rico", shortName: "PR" },
  { longName: "Qatar", shortName: "QA" },
  { longName: "RWANDA", shortName: "RW" },
  { longName: "Reunion", shortName: "RE" },
  { longName: "Romania", shortName: "RO" },
  { longName: "Russian Federation", shortName: "RU" },
  { longName: "Saint Barthelemy", shortName: "BL" },
  { longName: "Saint Helena", shortName: "SH" },
  { longName: "Saint Kitts and Nevis", shortName: "KN" },
  { longName: "Saint Lucia", shortName: "LC" },
  { longName: "Saint Martin", shortName: "MF" },
  { longName: "Saint Pierre and Miquelon", shortName: "PM" },
  { longName: "Saint Vincent and the Grenadines", shortName: "VC" },
  { longName: "Samoa", shortName: "WS" },
  { longName: "San Marino", shortName: "SM" },
  { longName: "Sao Tome and Principe", shortName: "ST" },
  { longName: "Saudi Arabia", shortName: "SA" },
  { longName: "Senegal", shortName: "SN" },
  { longName: "Serbia", shortName: "RS" },
  { longName: "Seychelles", shortName: "SC" },
  { longName: "Sierra Leone", shortName: "SL" },
  { longName: "Singapore", shortName: "SG" },
  { longName: "Sint Maarten", shortName: "SX" },
  { longName: "Slovakia", shortName: "SK" },
  { longName: "Slovenia", shortName: "SI" },
  { longName: "Solomon Islands", shortName: "SB" },
  { longName: "Somalia", shortName: "SO" },
  { longName: "South Africa", shortName: "ZA" },
  { longName: "South Georgia and the South Sandwich Islands", shortName: "GS" },
  { longName: "South Sudan", shortName: "SS" },
  { longName: "Spain", shortName: "ES" },
  { longName: "Sri Lanka", shortName: "LK" },
  { longName: "Sudan", shortName: "SD" },
  { longName: "SurilongName", shortName: "SR" },
  { longName: "Svalbard and Jan Mayen", shortName: "SJ" },
  { longName: "Swaziland", shortName: "SZ" },
  { longName: "Sweden", shortName: "SE" },
  { longName: "Switzerland", shortName: "CH" },
  { longName: "Syrian Arab Republic", shortName: "SY" },
  { longName: "Taiwan", shortName: "TW" },
  { longName: "Tajikistan", shortName: "TJ" },
  { longName: "Tanzania, United Republic of", shortName: "TZ" },
  { longName: "Thailand", shortName: "TH" },
  { longName: "Timor-Leste", shortName: "TL" },
  { longName: "Togo", shortName: "TG" },
  { longName: "Tokelau", shortName: "TK" },
  { longName: "Tonga", shortName: "TO" },
  { longName: "Trinidad and Tobago", shortName: "TT" },
  { longName: "Tunisia", shortName: "TN" },
  { longName: "Turkey", shortName: "TR" },
  { longName: "Turkmenistan", shortName: "TM" },
  { longName: "Turks and Caicos Islands", shortName: "TC" },
  { longName: "Tuvalu", shortName: "TV" },
  { longName: "Uganda", shortName: "UG" },
  { longName: "Ukraine", shortName: "UA" },
  { longName: "United Arab Emirates", shortName: "AE" },
  { longName: "United Kingdom", shortName: "GB" },
  { longName: "United States Minor Outlying Islands", shortName: "UM" },
  { longName: "Uruguay", shortName: "UY" },
  { longName: "Uzbekistan", shortName: "UZ" },
  { longName: "Vanuatu", shortName: "VU" },
  { longName: "Venezuela", shortName: "VE" },
  { longName: "Viet Nam", shortName: "VN" },
  { longName: "Vietnam", shortName: "VN" },
  { longName: "Virgin Islands, British", shortName: "VG" },
  { longName: "Virgin Islands, U.S.", shortName: "VI" },
  { longName: "Wallis and Futuna", shortName: "WF" },
  { longName: "Western Sahara", shortName: "EH" },
  { longName: "Yemen", shortName: "YE" },
  { longName: "Zambia", shortName: "ZM" },
  { longName: "Zimbabwe", shortName: "ZW" },
  { longName: "Åland Islands", shortName: "AX" }
];
